# Generated by Django 4.1 on 2022-12-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_img', models.BinaryField()),
                ('compName', models.CharField(max_length=70)),
                ('compDesc', models.CharField(max_length=200)),
                ('compURL', models.URLField()),
            ],
        ),
    ]
