# Generated by Django 4.1 on 2022-12-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='comp_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
